// routes.js — AUTO-GENERATED by scripts/routes-generator.js
// Do not edit manually. Run: npm run generate:routes

export const routes = [
  {
    "path": "/",
    "changefreq": "weekly",
    "priority": 1
  },
  {
    "path": "/blog",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-i-got-3m-visits",
    "changefreq": "monthly",
    "priority": 0.8
  },
  {
    "path": "/project/backtothefuture-clock",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/brawl-stars-pet-simulator",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/brawl-stars-rng",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/cube-generator",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/first-portfolio",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/koalaz",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/langrank",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/parolora-clock",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/physicshub",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/plugin-heatmap",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/plugin-sniper",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/plugin-ui-assistant",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/stackfingerprint",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/watermark-applier",
    "changefreq": "monthly",
    "priority": 0.7
  }
];
