// routes.js — AUTO-GENERATED by scripts/routes-generator.js
// Do not edit manually. Run: npm run generate:routes

export const routes = [
  {
    "path": "/",
    "changefreq": "weekly",
    "priority": 1
  },
  {
    "path": "/blog",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/5-common-react-rendering-mistakes",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/discover-tailwind-css",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-i-got-3m-visits",
    "changefreq": "monthly",
    "priority": 0.8
  },
  {
    "path": "/blog/how-to-handle-c++-memory-like-a-pro",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-to-mae-a-good-dark-mode-design",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-to-make-datastore-more-safe-roblox-studio",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-to-make-good-roblox-games-with-ux",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-to-make-your-UIs-with-figma",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-to-write-code-like-a-pro-roblox-studio",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/make-your-player-addicted-to-your-roblox-game",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/project/backtothefuture-clock",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/brawl-stars-pet-simulator",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/brawl-stars-rng",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/cube-generator",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/famous-roblox-users-finder",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/first-portfolio",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/koalaz",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/langrank",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/parolora-clock",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/physicshub",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/plugin-heatmap",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/plugin-sniper",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/plugin-ui-assistant",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/stackfingerprint",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/project/watermark-applier",
    "changefreq": "monthly",
    "priority": 0.7
  }
];
