// routes.js — AUTO-GENERATED by scripts/routes-generator.js
// Do not edit manually. Run: npm run generate:routes

export const routes = [
  {
    "path": "/",
    "changefreq": "weekly",
    "priority": 1
  },
  {
    "path": "/blog",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/5-common-react-rendering-mistakes",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/discover-tailwind-css",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-i-got-3m-visits",
    "changefreq": "monthly",
    "priority": 0.8
  },
  {
    "path": "/blog/how-to-handle-cplusplus-memory-like-a-pro",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-to-make-a-good-dark-mode-design",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-to-make-datastore-more-safe-roblox-studio",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-to-make-good-roblox-games-with-ux",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-to-make-your-UIs-with-figma",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-to-write-code-like-a-pro-roblox-studio",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/make-your-player-addicted-to-your-roblox-game",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/arduino-millis-instead-of-delay",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/deploy-nextjs-to-github-pages",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/fix-100vh-mobile-browsers-css-dvh",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/fix-hydration-error-nextjs",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/fix-infinite-yield-possible-waitforchild-roblox",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/fix-memory-leaks-luau-connections-roblox",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/github-api-rate-limit-static-site",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-to-build-finite-state-machine-in-luau-roblox-npc",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-to-publish-your-first-npm-package",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/how-to-secure-remoteevents-from-exploiters-roblox",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/profileservice-datastore-in-roblox-studio-2026-developer-guide",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/server-components-vs-client-components-react-framework",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/why-does-useeffect-run-twice-react",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/datastore-lock-lost-roblox-fix",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/blog/roblox-data-loss-what-to-do-2026",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/projects",
    "changefreq": "weekly",
    "priority": 0.9
  },
  {
    "path": "/projects/backtothefuture-clock",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/brawl-stars-pet-simulator",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/brawl-stars-rng",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/cube-generator",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/famous-roblox-users-finder",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/first-portfolio",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/goalmageddon",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/koalaz",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/langrank",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/parolora-clock",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/physicshub",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/plugin-heatmap",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/plugin-sniper",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/plugin-ui-assistant",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/portfolio",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/stackfingerprint",
    "changefreq": "monthly",
    "priority": 0.7
  },
  {
    "path": "/projects/watermark-applier",
    "changefreq": "monthly",
    "priority": 0.7
  }
];
